### ISSUE TITLE
Extra hash mark in xref

### ISSUE THREAD

**Issue by pmkovar** [lruzicka/sphinx_asciidoc#14]
Eg. in https://github.com/openstack/openstack-manuals/blob/master/doc/doc-contrib-guide/source/blueprints-and-specs.rst:

```
For more information, see :ref:`doc_bugs`.
```
Result:
```
For more information, see xref:#doc-bugs[Documentation bugs].
```
Expected:
```
For more information, see xref:doc-bugs[Documentation bugs].
```

**Comment by lruzicka** [comment]
I see it differently. In the above given file, there is this line:
`For more information, see :ref:`doc_bugs`. `

And in the ascii doc file, there is this line:
`For more information, see xref:doc-bugs.adoc#doc-bugs[Documentation bugs].`

To me it seems that the output is correct, because it points to the `doc-bugs` in the **doc-bugs.adoc.** The question is, if it is supported in asciidoc and if it needs to be dealt with somehow.

**Comment by lruzicka** [comment]
For the time's being I have stripped the file information from the reference line.
